#ifndef SYMGEN_PYTHON_BINDINGS_BIND_DEPENDENCY_HPP
#define SYMGEN_PYTHON_BINDINGS_BIND_DEPENDENCY_HPP

#include <pybind11/pybind11.h>

void bind_dependency(pybind11::module_& m);

#endif // SYMGEN_PYTHON_BINDINGS_BIND_DEPENDENCY_HPP
