########################################################################
####                       demos subdirectory                       ####
########################################################################

########################################################################
####                          Dependencies                          ####
########################################################################

########################################################################
####                            Targets                             ####
########################################################################

add_library(demos_include INTERFACE)

add_executable(demo_cmake)

########################################################################
####                            Sources                             ####
########################################################################

target_sources(demo_cmake PRIVATE
	src/demo_cmake.cpp)

target_include_directories(demos_include INTERFACE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>)

########################################################################
####                              Link                              ####
########################################################################

target_link_libraries(demo_cmake
	PRIVATE demos_include
	PRIVATE SymGen)

